/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCharacterModal: typeof import('./src/components/modals/AddCharacterModal.vue')['default']
    AddChatModal: typeof import('./src/components/modals/AddChatModal.vue')['default']
    AddModelModal: typeof import('./src/components/modals/AddModelModal.vue')['default']
    AddParticipantModal: typeof import('./src/components/modals/AddParticipantModal.vue')['default']
    AddPresetModal: typeof import('./src/components/modals/AddPresetModal.vue')['default']
    AddProviderModal: typeof import('./src/components/modals/AddProviderModal.vue')['default']
    AddTemplateModal: typeof import('./src/components/modals/AddTemplateModal.vue')['default']
    AddTranslatorModal: typeof import('./src/components/modals/AddTranslatorModal.vue')['default']
    AddUserModal: typeof import('./src/components/modals/AddUserModal.vue')['default']
    CharacterSettings: typeof import('./src/components/settings/CharacterSettings.vue')['default']
    ChatBox: typeof import('./src/components/ChatBox.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    EditCharacterModal: typeof import('./src/components/modals/EditCharacterModal.vue')['default']
    EditChatModal: typeof import('./src/components/modals/EditChatModal.vue')['default']
    EditModelModal: typeof import('./src/components/modals/EditModelModal.vue')['default']
    EditParticipantModal: typeof import('./src/components/modals/EditParticipantModal.vue')['default']
    EditPresetModal: typeof import('./src/components/modals/EditPresetModal.vue')['default']
    EditProviderModal: typeof import('./src/components/modals/EditProviderModal.vue')['default']
    EditTemplateModal: typeof import('./src/components/modals/EditTemplateModal.vue')['default']
    EditUserModal: typeof import('./src/components/modals/EditUserModal.vue')['default']
    GeneralSettings: typeof import('./src/components/settings/GeneralSettings.vue')['default']
    PresetSettings: typeof import('./src/components/settings/PresetSettings.vue')['default']
    ProviderSettings: typeof import('./src/components/settings/ProviderSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDynamicInput: typeof import('./src/components/SettingsDynamicInput.vue')['default']
    SettingsDynamicSelect: typeof import('./src/components/SettingsDynamicSelect.vue')['default']
    SettingsInput: typeof import('./src/components/SettingsInput.vue')['default']
    SettingsNumberInput: typeof import('./src/components/SettingsNumberInput.vue')['default']
    SettingsSwitch: typeof import('./src/components/SettingsSwitch.vue')['default']
    TemplateSettings: typeof import('./src/components/settings/TemplateSettings.vue')['default']
    UserSettings: typeof import('./src/components/settings/UserSettings.vue')['default']
  }
}
